name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Check Format
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

  test-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          include_prerelease: false

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.latest_version }}"
